name: CI

on:
  push:
    branches: [ main ]
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
  pull_request:
    branches: [ main ]


env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: clippy
    - name: Annotate commit with clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features --all
  
  build_test_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Test
      run: cargo test --verbose
    - name: Release build
      run: cargo build --release --verbose
    - name: Copy binary
      if: hashFiles('target/release/cryptopuzzle')
      run: |
        cp target/release/cryptopuzzle cryptopuzzle-${{ runner.os }}
    - name: Copy binary (Windows)
      if: hashFiles('target/release/cryptopuzzle.exe')
      run: |
        copy target/release/cryptopuzzle.exe cryptopuzzle-${{ runner.os }}.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cryptopuzzle
        path: cryptopuzzle-${{ runner.os }}*

  pre_release:
    needs: build_test_deploy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: cryptopuzzle
    - name: Deploy pre-release to github.com
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-build"
        prerelease: true
        title: "Latest build on commit"
        files: |
          cryptopuzzle-*
 
  release:
    needs: build_test_deploy
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
    - uses: actions/checkout@v3
    - uses: ericcornelissen/git-tag-annotation-action@v2
      id: tag_data
    - name: Get the version
      id: get_version
      run: echo "name=VERSION::${GITHUB_REF/refs\/tags\//}" > $GITHUB_OUTPUT
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: cryptopuzzle
    - name: Deploy release to github.com
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
        prerelease: false
        title: ${{ steps.get_version.outputs.VERSION }}
        files: |
          cryptopuzzle-*

